# Generated by Django 4.0.2 on 2022-02-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Cloud')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Providers/', verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Nube',
                'verbose_name_plural': 'Nubes',
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cloud.provider', verbose_name='Nube')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Services/', verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cloud.typeservice', verbose_name='Tipo de servicio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cloud.provider', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
    ]
