# Generated by Django 4.0.2 on 2022-02-09 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Area')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start.area', verbose_name='Area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('liable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start.employee', verbose_name='Responsable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Cargo')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de actualización')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Correo')),
                ('fullname', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre completo')),
                ('names', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombres')),
                ('surname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellidos')),
                ('document_type', models.CharField(blank=True, choices=[('dni', 'DNI'), ('ce', 'Carnet de extranjería'), ('pasaporte', 'Pasaporte')], max_length=9, null=True, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Número de documento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start.person', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start.position', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
