# Generated by Django 4.1.7 on 2023-03-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='area',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='person',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='liable',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
